/*
 * Wiz Processor API
 * This is the HTTP + JSON + REST version of the Wiz Processor API.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WizProcessorApi);
  }
}(this, function(expect, WizProcessorApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProcessorsRun', function() {
      beforeEach(function() {
        instance = new WizProcessorApi.ProcessorsRun();
      });

      it('should create an instance of ProcessorsRun', function() {
        // TODO: update the code to test ProcessorsRun
        expect(instance).to.be.a(WizProcessorApi.ProcessorsRun);
      });

      it('should have the property configuration (base name: "Configuration")', function() {
        // TODO: update the code to test the property configuration
        expect(instance).to.have.property('configuration');
        // expect(instance.configuration).to.be(expectedValueLiteral);
      });

      it('should have the property currentState (base name: "CurrentState")', function() {
        // TODO: update the code to test the property currentState
        expect(instance).to.have.property('currentState');
        // expect(instance.currentState).to.be(expectedValueLiteral);
      });

      it('should have the property runID (base name: "RunID")', function() {
        // TODO: update the code to test the property runID
        expect(instance).to.have.property('runID');
        // expect(instance.runID).to.be(expectedValueLiteral);
      });

    });
  });

}));
