/*
 * Wiz Processor API
 * This is the HTTP + JSON + REST version of the Wiz Processor API.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WizProcessorApi);
  }
}(this, function(expect, WizProcessorApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProcessorsExecutorConfig', function() {
      beforeEach(function() {
        instance = new WizProcessorApi.ProcessorsExecutorConfig();
      });

      it('should create an instance of ProcessorsExecutorConfig', function() {
        // TODO: update the code to test ProcessorsExecutorConfig
        expect(instance).to.be.a(WizProcessorApi.ProcessorsExecutorConfig);
      });

      it('should have the property downstreamLocations (base name: "DownstreamLocations")', function() {
        // TODO: update the code to test the property downstreamLocations
        expect(instance).to.have.property('downstreamLocations');
        // expect(instance.downstreamLocations).to.be(expectedValueLiteral);
      });

      it('should have the property maxWorkers (base name: "MaxWorkers")', function() {
        // TODO: update the code to test the property maxWorkers
        expect(instance).to.have.property('maxWorkers');
        // expect(instance.maxWorkers).to.be(expectedValueLiteral);
      });

      it('should have the property sendDownstream (base name: "SendDownstream")', function() {
        // TODO: update the code to test the property sendDownstream
        expect(instance).to.have.property('sendDownstream');
        // expect(instance.sendDownstream).to.be(expectedValueLiteral);
      });

    });
  });

}));
