/*
 * Wiz Processor API
 * This is the HTTP + JSON + REST version of the Wiz Processor API.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WizProcessorApi);
  }
}(this, function(expect, WizProcessorApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProcessorsData', function() {
      beforeEach(function() {
        instance = new WizProcessorApi.ProcessorsData();
      });

      it('should create an instance of ProcessorsData', function() {
        // TODO: update the code to test ProcessorsData
        expect(instance).to.be.a(WizProcessorApi.ProcessorsData);
      });

      it('should have the property associatedChunkID (base name: "AssociatedChunkID")', function() {
        // TODO: update the code to test the property associatedChunkID
        expect(instance).to.have.property('associatedChunkID');
        // expect(instance.associatedChunkID).to.be(expectedValueLiteral);
      });

      it('should have the property chunkID (base name: "ChunkID")', function() {
        // TODO: update the code to test the property chunkID
        expect(instance).to.have.property('chunkID');
        // expect(instance.chunkID).to.be(expectedValueLiteral);
      });

      it('should have the property filesystemReference (base name: "FilesystemReference")', function() {
        // TODO: update the code to test the property filesystemReference
        expect(instance).to.have.property('filesystemReference');
        // expect(instance.filesystemReference).to.be(expectedValueLiteral);
      });

      it('should have the property format (base name: "Format")', function() {
        // TODO: update the code to test the property format
        expect(instance).to.have.property('format');
        // expect(instance.format).to.be(expectedValueLiteral);
      });

      it('should have the property rawData (base name: "RawData")', function() {
        // TODO: update the code to test the property rawData
        expect(instance).to.have.property('rawData');
        // expect(instance.rawData).to.be(expectedValueLiteral);
      });

      it('should have the property state (base name: "State")', function() {
        // TODO: update the code to test the property state
        expect(instance).to.have.property('state');
        // expect(instance.state).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "Type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
