/*
 * Wiz Processor API
 * This is the HTTP + JSON + REST version of the Wiz Processor API.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WizProcessorApi);
  }
}(this, function(expect, WizProcessorApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProcessorsExpectedData', function() {
      beforeEach(function() {
        instance = new WizProcessorApi.ProcessorsExpectedData();
      });

      it('should create an instance of ProcessorsExpectedData', function() {
        // TODO: update the code to test ProcessorsExpectedData
        expect(instance).to.be.a(WizProcessorApi.ProcessorsExpectedData);
      });

      it('should have the property numChunks (base name: "NumChunks")', function() {
        // TODO: update the code to test the property numChunks
        expect(instance).to.have.property('numChunks');
        // expect(instance.numChunks).to.be(expectedValueLiteral);
      });

    });
  });

}));
