/*
 * Wiz Processor API
 * This is the HTTP + JSON + REST version of the Wiz Processor API.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProcessorsExecutorConfig', 'model/ProcessorsExpectedData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProcessorsExecutorConfig'), require('./ProcessorsExpectedData'));
  } else {
    // Browser globals (root is window)
    if (!root.WizProcessorApi) {
      root.WizProcessorApi = {};
    }
    root.WizProcessorApi.ProcessorsConfiguration = factory(root.WizProcessorApi.ApiClient, root.WizProcessorApi.ProcessorsExecutorConfig, root.WizProcessorApi.ProcessorsExpectedData);
  }
}(this, function(ApiClient, ProcessorsExecutorConfig, ProcessorsExpectedData) {
  'use strict';

  /**
   * The ProcessorsConfiguration model module.
   * @module model/ProcessorsConfiguration
   * @version 1.0
   */

  /**
   * Constructs a new <code>ProcessorsConfiguration</code>.
   * @alias module:model/ProcessorsConfiguration
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ProcessorsConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProcessorsConfiguration} obj Optional instance to populate.
   * @return {module:model/ProcessorsConfiguration} The populated <code>ProcessorsConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ExecutorConfig'))
        obj.executorConfig = ProcessorsExecutorConfig.constructFromObject(data['ExecutorConfig']);
      if (data.hasOwnProperty('ExpectedData'))
        obj.expectedData = ProcessorsExpectedData.constructFromObject(data['ExpectedData']);
      if (data.hasOwnProperty('Processor'))
        obj.processor = ApiClient.convertToType(data['Processor'], Object);
    }
    return obj;
  }

  /**
   * @member {module:model/ProcessorsExecutorConfig} executorConfig
   */
  exports.prototype.executorConfig = undefined;

  /**
   * Embeded structs have a weird JSON serialization issue
   * @member {module:model/ProcessorsExpectedData} expectedData
   */
  exports.prototype.expectedData = undefined;

  /**
   * @member {Object} processor
   */
  exports.prototype.processor = undefined;

  return exports;

}));
