/*
 * Wiz Processor API
 * This is the HTTP + JSON + REST version of the Wiz Processor API.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProcessorsData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProcessorsData'));
  } else {
    // Browser globals (root is window)
    if (!root.WizProcessorApi) {
      root.WizProcessorApi = {};
    }
    root.WizProcessorApi.ProcessorsDataSpec = factory(root.WizProcessorApi.ApiClient, root.WizProcessorApi.ProcessorsData);
  }
}(this, function(ApiClient, ProcessorsData) {
  'use strict';

  /**
   * The ProcessorsDataSpec model module.
   * @module model/ProcessorsDataSpec
   * @version 1.0
   */

  /**
   * Constructs a new <code>ProcessorsDataSpec</code>.
   * @alias module:model/ProcessorsDataSpec
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ProcessorsDataSpec</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProcessorsDataSpec} obj Optional instance to populate.
   * @return {module:model/ProcessorsDataSpec} The populated <code>ProcessorsDataSpec</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('In'))
        obj._in = ApiClient.convertToType(data['In'], [ProcessorsData]);
      if (data.hasOwnProperty('Out'))
        obj.out = ApiClient.convertToType(data['Out'], [ProcessorsData]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ProcessorsData>} _in
   */
  exports.prototype._in = undefined;

  /**
   * @member {Array.<module:model/ProcessorsData>} out
   */
  exports.prototype.out = undefined;

  return exports;

}));
