/*
 * Wiz Processor API
 * This is the HTTP + JSON + REST version of the Wiz Processor API.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProcessorsConfiguration', 'model/ProcessorsData', 'model/ProcessorsDataSpec', 'model/ProcessorsDownstreamDataLocation', 'model/ProcessorsExecutorConfig', 'model/ProcessorsExpectedData', 'model/ProcessorsFilesystemReference', 'model/ProcessorsProcessor', 'model/ProcessorsProcessors', 'model/ProcessorsRun', 'model/ProcessorsRuns', 'model/ServerEmpty', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ProcessorsConfiguration'), require('./model/ProcessorsData'), require('./model/ProcessorsDataSpec'), require('./model/ProcessorsDownstreamDataLocation'), require('./model/ProcessorsExecutorConfig'), require('./model/ProcessorsExpectedData'), require('./model/ProcessorsFilesystemReference'), require('./model/ProcessorsProcessor'), require('./model/ProcessorsProcessors'), require('./model/ProcessorsRun'), require('./model/ProcessorsRuns'), require('./model/ServerEmpty'), require('./api/DefaultApi'));
  }
}(function(ApiClient, ProcessorsConfiguration, ProcessorsData, ProcessorsDataSpec, ProcessorsDownstreamDataLocation, ProcessorsExecutorConfig, ProcessorsExpectedData, ProcessorsFilesystemReference, ProcessorsProcessor, ProcessorsProcessors, ProcessorsRun, ProcessorsRuns, ServerEmpty, DefaultApi) {
  'use strict';

  /**
   * This_is_the_HTTP__JSON__REST_version_of_the_Wiz_Processor_API_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var WizProcessorApi = require('index'); // See note below*.
   * var xxxSvc = new WizProcessorApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new WizProcessorApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new WizProcessorApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new WizProcessorApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ProcessorsConfiguration model constructor.
     * @property {module:model/ProcessorsConfiguration}
     */
    ProcessorsConfiguration: ProcessorsConfiguration,
    /**
     * The ProcessorsData model constructor.
     * @property {module:model/ProcessorsData}
     */
    ProcessorsData: ProcessorsData,
    /**
     * The ProcessorsDataSpec model constructor.
     * @property {module:model/ProcessorsDataSpec}
     */
    ProcessorsDataSpec: ProcessorsDataSpec,
    /**
     * The ProcessorsDownstreamDataLocation model constructor.
     * @property {module:model/ProcessorsDownstreamDataLocation}
     */
    ProcessorsDownstreamDataLocation: ProcessorsDownstreamDataLocation,
    /**
     * The ProcessorsExecutorConfig model constructor.
     * @property {module:model/ProcessorsExecutorConfig}
     */
    ProcessorsExecutorConfig: ProcessorsExecutorConfig,
    /**
     * The ProcessorsExpectedData model constructor.
     * @property {module:model/ProcessorsExpectedData}
     */
    ProcessorsExpectedData: ProcessorsExpectedData,
    /**
     * The ProcessorsFilesystemReference model constructor.
     * @property {module:model/ProcessorsFilesystemReference}
     */
    ProcessorsFilesystemReference: ProcessorsFilesystemReference,
    /**
     * The ProcessorsProcessor model constructor.
     * @property {module:model/ProcessorsProcessor}
     */
    ProcessorsProcessor: ProcessorsProcessor,
    /**
     * The ProcessorsProcessors model constructor.
     * @property {module:model/ProcessorsProcessors}
     */
    ProcessorsProcessors: ProcessorsProcessors,
    /**
     * The ProcessorsRun model constructor.
     * @property {module:model/ProcessorsRun}
     */
    ProcessorsRun: ProcessorsRun,
    /**
     * The ProcessorsRuns model constructor.
     * @property {module:model/ProcessorsRuns}
     */
    ProcessorsRuns: ProcessorsRuns,
    /**
     * The ServerEmpty model constructor.
     * @property {module:model/ServerEmpty}
     */
    ServerEmpty: ServerEmpty,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
